version: "3.3"
services:
  db:
    image: mysql:8.0.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - ./localdb/my-docker.cnf:/etc/my.cnf:delegated
      - db_volume:/var/lib/mysql:delegated
    ports:
      - "43306:3306"
volumes:
  db_volume:
